/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MissedCallRouteImport } from './routes/missed-call'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAiReceptionistRouteImport } from './routes/_authenticated/ai-receptionist'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMissedCallSettingsRouteImport } from './routes/_authenticated/missed-call-settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as ServicesBlockedDrainsRouteImport } from './routes/services.blocked-drains'
import { Route as ServicesEmergencyRouteImport } from './routes/services.emergency'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiDashboardVerifyPinRouteImport } from './routes/api/dashboard.verify-pin'
import { Route as ApiDemoTriggerSmsRouteImport } from './routes/api/demo.trigger-sms'
import { Route as ApiPublicProcessEnrichmentJobsRouteImport } from './routes/api/public/process-enrichment-jobs'
import { Route as ApiWebhooksAiPhoneLeadRouteImport } from './routes/api/webhooks.ai-phone-lead'
import { Route as BSlugIndexRouteImport } from './routes/b.$slug.index'
import { Route as BSlugChatRouteImport } from './routes/b.$slug.chat'
import { Route as BSlugConfirmationRouteImport } from './routes/b.$slug.confirmation'
import { Route as BSlugMissedCallRouteImport } from './routes/b.$slug.missed-call'
import { Route as BSlugRequestRouteImport } from './routes/b.$slug.request'
import { Route as ApiPublicBillingCheckoutRouteImport } from './routes/api/public/billing.checkout'
import { Route as ApiPublicBillingPortalRouteImport } from './routes/api/public/billing.portal'
import { Route as ApiPublicBillingSummaryRouteImport } from './routes/api/public/billing.summary'
import { Route as ApiPublicWebhooksStripeInboundRouteImport } from './routes/api/public/webhooks.stripe-inbound'
import { Route as ApiPublicWebhooksVapiInboundRouteImport } from './routes/api/public/webhooks.vapi-inbound'
import { Route as ApiPublicWebhooksTwilioMissedCallSlugRouteImport } from './routes/api/public.webhooks.twilio-missed-call.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MissedCallRoute = MissedCallRouteImport.update({
  id: '/missed-call',
  path: '/missed-call',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAiReceptionistRoute =
  AuthenticatedAiReceptionistRouteImport.update({
    id: '/ai-receptionist',
    path: '/ai-receptionist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMissedCallSettingsRoute =
  AuthenticatedMissedCallSettingsRouteImport.update({
    id: '/missed-call-settings',
    path: '/missed-call-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBlockedDrainsRoute = ServicesBlockedDrainsRouteImport.update({
  id: '/services/blocked-drains',
  path: '/services/blocked-drains',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEmergencyRoute = ServicesEmergencyRouteImport.update({
  id: '/services/emergency',
  path: '/services/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDashboardVerifyPinRoute = ApiDashboardVerifyPinRouteImport.update({
  id: '/api/dashboard/verify-pin',
  path: '/api/dashboard/verify-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoTriggerSmsRoute = ApiDemoTriggerSmsRouteImport.update({
  id: '/api/demo/trigger-sms',
  path: '/api/demo/trigger-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProcessEnrichmentJobsRoute =
  ApiPublicProcessEnrichmentJobsRouteImport.update({
    id: '/api/public/process-enrichment-jobs',
    path: '/api/public/process-enrichment-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksAiPhoneLeadRoute = ApiWebhooksAiPhoneLeadRouteImport.update({
  id: '/api/webhooks/ai-phone-lead',
  path: '/api/webhooks/ai-phone-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugIndexRoute = BSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BSlugRoute,
} as any)
const BSlugChatRoute = BSlugChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => BSlugRoute,
} as any)
const BSlugConfirmationRoute = BSlugConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => BSlugRoute,
} as any)
const BSlugMissedCallRoute = BSlugMissedCallRouteImport.update({
  id: '/missed-call',
  path: '/missed-call',
  getParentRoute: () => BSlugRoute,
} as any)
const BSlugRequestRoute = BSlugRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => BSlugRoute,
} as any)
const ApiPublicBillingCheckoutRoute =
  ApiPublicBillingCheckoutRouteImport.update({
    id: '/api/public/billing/checkout',
    path: '/api/public/billing/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBillingPortalRoute = ApiPublicBillingPortalRouteImport.update({
  id: '/api/public/billing/portal',
  path: '/api/public/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBillingSummaryRoute = ApiPublicBillingSummaryRouteImport.update({
  id: '/api/public/billing/summary',
  path: '/api/public/billing/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksStripeInboundRoute =
  ApiPublicWebhooksStripeInboundRouteImport.update({
    id: '/api/public/webhooks/stripe-inbound',
    path: '/api/public/webhooks/stripe-inbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksVapiInboundRoute =
  ApiPublicWebhooksVapiInboundRouteImport.update({
    id: '/api/public/webhooks/vapi-inbound',
    path: '/api/public/webhooks/vapi-inbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksTwilioMissedCallSlugRoute =
  ApiPublicWebhooksTwilioMissedCallSlugRouteImport.update({
    id: '/api/public/webhooks/twilio-missed-call/$slug',
    path: '/api/public/webhooks/twilio-missed-call/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas': typeof AreasRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/confirmation': typeof ConfirmationRoute
  '/mcp': typeof McpRoute
  '/missed-call': typeof MissedCallRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ai-receptionist': typeof AuthenticatedAiReceptionistRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/missed-call-settings': typeof AuthenticatedMissedCallSettingsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/services/blocked-drains': typeof ServicesBlockedDrainsRoute
  '/services/emergency': typeof ServicesEmergencyRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/dashboard/verify-pin': typeof ApiDashboardVerifyPinRoute
  '/api/demo/trigger-sms': typeof ApiDemoTriggerSmsRoute
  '/api/public/process-enrichment-jobs': typeof ApiPublicProcessEnrichmentJobsRoute
  '/api/webhooks/ai-phone-lead': typeof ApiWebhooksAiPhoneLeadRoute
  '/b/$slug/chat': typeof BSlugChatRoute
  '/b/$slug/confirmation': typeof BSlugConfirmationRoute
  '/b/$slug/missed-call': typeof BSlugMissedCallRoute
  '/b/$slug/request': typeof BSlugRequestRoute
  '/b/$slug/': typeof BSlugIndexRoute
  '/api/public/billing/checkout': typeof ApiPublicBillingCheckoutRoute
  '/api/public/billing/portal': typeof ApiPublicBillingPortalRoute
  '/api/public/billing/summary': typeof ApiPublicBillingSummaryRoute
  '/api/public/webhooks/stripe-inbound': typeof ApiPublicWebhooksStripeInboundRoute
  '/api/public/webhooks/vapi-inbound': typeof ApiPublicWebhooksVapiInboundRoute
  '/api/public/webhooks/twilio-missed-call/$slug': typeof ApiPublicWebhooksTwilioMissedCallSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areas': typeof AreasRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/confirmation': typeof ConfirmationRoute
  '/mcp': typeof McpRoute
  '/missed-call': typeof MissedCallRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ai-receptionist': typeof AuthenticatedAiReceptionistRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/missed-call-settings': typeof AuthenticatedMissedCallSettingsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/services/blocked-drains': typeof ServicesBlockedDrainsRoute
  '/services/emergency': typeof ServicesEmergencyRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/dashboard/verify-pin': typeof ApiDashboardVerifyPinRoute
  '/api/demo/trigger-sms': typeof ApiDemoTriggerSmsRoute
  '/api/public/process-enrichment-jobs': typeof ApiPublicProcessEnrichmentJobsRoute
  '/api/webhooks/ai-phone-lead': typeof ApiWebhooksAiPhoneLeadRoute
  '/b/$slug/chat': typeof BSlugChatRoute
  '/b/$slug/confirmation': typeof BSlugConfirmationRoute
  '/b/$slug/missed-call': typeof BSlugMissedCallRoute
  '/b/$slug/request': typeof BSlugRequestRoute
  '/b/$slug': typeof BSlugIndexRoute
  '/api/public/billing/checkout': typeof ApiPublicBillingCheckoutRoute
  '/api/public/billing/portal': typeof ApiPublicBillingPortalRoute
  '/api/public/billing/summary': typeof ApiPublicBillingSummaryRoute
  '/api/public/webhooks/stripe-inbound': typeof ApiPublicWebhooksStripeInboundRoute
  '/api/public/webhooks/vapi-inbound': typeof ApiPublicWebhooksVapiInboundRoute
  '/api/public/webhooks/twilio-missed-call/$slug': typeof ApiPublicWebhooksTwilioMissedCallSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/areas': typeof AreasRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/confirmation': typeof ConfirmationRoute
  '/mcp': typeof McpRoute
  '/missed-call': typeof MissedCallRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/ai-receptionist': typeof AuthenticatedAiReceptionistRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/missed-call-settings': typeof AuthenticatedMissedCallSettingsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/services/blocked-drains': typeof ServicesBlockedDrainsRoute
  '/services/emergency': typeof ServicesEmergencyRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/dashboard/verify-pin': typeof ApiDashboardVerifyPinRoute
  '/api/demo/trigger-sms': typeof ApiDemoTriggerSmsRoute
  '/api/public/process-enrichment-jobs': typeof ApiPublicProcessEnrichmentJobsRoute
  '/api/webhooks/ai-phone-lead': typeof ApiWebhooksAiPhoneLeadRoute
  '/b/$slug/chat': typeof BSlugChatRoute
  '/b/$slug/confirmation': typeof BSlugConfirmationRoute
  '/b/$slug/missed-call': typeof BSlugMissedCallRoute
  '/b/$slug/request': typeof BSlugRequestRoute
  '/b/$slug/': typeof BSlugIndexRoute
  '/api/public/billing/checkout': typeof ApiPublicBillingCheckoutRoute
  '/api/public/billing/portal': typeof ApiPublicBillingPortalRoute
  '/api/public/billing/summary': typeof ApiPublicBillingSummaryRoute
  '/api/public/webhooks/stripe-inbound': typeof ApiPublicWebhooksStripeInboundRoute
  '/api/public/webhooks/vapi-inbound': typeof ApiPublicWebhooksVapiInboundRoute
  '/api/public/webhooks/twilio-missed-call/$slug': typeof ApiPublicWebhooksTwilioMissedCallSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/areas'
    | '/auth'
    | '/chat'
    | '/confirmation'
    | '/mcp'
    | '/missed-call'
    | '/request'
    | '/reset-password'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ai-receptionist'
    | '/billing'
    | '/dashboard'
    | '/missed-call-settings'
    | '/onboarding'
    | '/settings'
    | '/b/$slug'
    | '/services/blocked-drains'
    | '/services/emergency'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/dashboard/verify-pin'
    | '/api/demo/trigger-sms'
    | '/api/public/process-enrichment-jobs'
    | '/api/webhooks/ai-phone-lead'
    | '/b/$slug/chat'
    | '/b/$slug/confirmation'
    | '/b/$slug/missed-call'
    | '/b/$slug/request'
    | '/b/$slug/'
    | '/api/public/billing/checkout'
    | '/api/public/billing/portal'
    | '/api/public/billing/summary'
    | '/api/public/webhooks/stripe-inbound'
    | '/api/public/webhooks/vapi-inbound'
    | '/api/public/webhooks/twilio-missed-call/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/areas'
    | '/auth'
    | '/chat'
    | '/confirmation'
    | '/mcp'
    | '/missed-call'
    | '/request'
    | '/reset-password'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ai-receptionist'
    | '/billing'
    | '/dashboard'
    | '/missed-call-settings'
    | '/onboarding'
    | '/settings'
    | '/services/blocked-drains'
    | '/services/emergency'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/dashboard/verify-pin'
    | '/api/demo/trigger-sms'
    | '/api/public/process-enrichment-jobs'
    | '/api/webhooks/ai-phone-lead'
    | '/b/$slug/chat'
    | '/b/$slug/confirmation'
    | '/b/$slug/missed-call'
    | '/b/$slug/request'
    | '/b/$slug'
    | '/api/public/billing/checkout'
    | '/api/public/billing/portal'
    | '/api/public/billing/summary'
    | '/api/public/webhooks/stripe-inbound'
    | '/api/public/webhooks/vapi-inbound'
    | '/api/public/webhooks/twilio-missed-call/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/areas'
    | '/auth'
    | '/chat'
    | '/confirmation'
    | '/mcp'
    | '/missed-call'
    | '/request'
    | '/reset-password'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/ai-receptionist'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/missed-call-settings'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/b/$slug'
    | '/services/blocked-drains'
    | '/services/emergency'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/dashboard/verify-pin'
    | '/api/demo/trigger-sms'
    | '/api/public/process-enrichment-jobs'
    | '/api/webhooks/ai-phone-lead'
    | '/b/$slug/chat'
    | '/b/$slug/confirmation'
    | '/b/$slug/missed-call'
    | '/b/$slug/request'
    | '/b/$slug/'
    | '/api/public/billing/checkout'
    | '/api/public/billing/portal'
    | '/api/public/billing/summary'
    | '/api/public/webhooks/stripe-inbound'
    | '/api/public/webhooks/vapi-inbound'
    | '/api/public/webhooks/twilio-missed-call/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AreasRoute: typeof AreasRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  ConfirmationRoute: typeof ConfirmationRoute
  McpRoute: typeof McpRoute
  MissedCallRoute: typeof MissedCallRoute
  RequestRoute: typeof RequestRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BSlugRoute: typeof BSlugRouteWithChildren
  ServicesBlockedDrainsRoute: typeof ServicesBlockedDrainsRoute
  ServicesEmergencyRoute: typeof ServicesEmergencyRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiDashboardVerifyPinRoute: typeof ApiDashboardVerifyPinRoute
  ApiDemoTriggerSmsRoute: typeof ApiDemoTriggerSmsRoute
  ApiPublicProcessEnrichmentJobsRoute: typeof ApiPublicProcessEnrichmentJobsRoute
  ApiWebhooksAiPhoneLeadRoute: typeof ApiWebhooksAiPhoneLeadRoute
  ApiPublicBillingCheckoutRoute: typeof ApiPublicBillingCheckoutRoute
  ApiPublicBillingPortalRoute: typeof ApiPublicBillingPortalRoute
  ApiPublicBillingSummaryRoute: typeof ApiPublicBillingSummaryRoute
  ApiPublicWebhooksStripeInboundRoute: typeof ApiPublicWebhooksStripeInboundRoute
  ApiPublicWebhooksVapiInboundRoute: typeof ApiPublicWebhooksVapiInboundRoute
  ApiPublicWebhooksTwilioMissedCallSlugRoute: typeof ApiPublicWebhooksTwilioMissedCallSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missed-call': {
      id: '/missed-call'
      path: '/missed-call'
      fullPath: '/missed-call'
      preLoaderRoute: typeof MissedCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-receptionist': {
      id: '/_authenticated/ai-receptionist'
      path: '/ai-receptionist'
      fullPath: '/ai-receptionist'
      preLoaderRoute: typeof AuthenticatedAiReceptionistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missed-call-settings': {
      id: '/_authenticated/missed-call-settings'
      path: '/missed-call-settings'
      fullPath: '/missed-call-settings'
      preLoaderRoute: typeof AuthenticatedMissedCallSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/blocked-drains': {
      id: '/services/blocked-drains'
      path: '/services/blocked-drains'
      fullPath: '/services/blocked-drains'
      preLoaderRoute: typeof ServicesBlockedDrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/emergency': {
      id: '/services/emergency'
      path: '/services/emergency'
      fullPath: '/services/emergency'
      preLoaderRoute: typeof ServicesEmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/verify-pin': {
      id: '/api/dashboard/verify-pin'
      path: '/api/dashboard/verify-pin'
      fullPath: '/api/dashboard/verify-pin'
      preLoaderRoute: typeof ApiDashboardVerifyPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/trigger-sms': {
      id: '/api/demo/trigger-sms'
      path: '/api/demo/trigger-sms'
      fullPath: '/api/demo/trigger-sms'
      preLoaderRoute: typeof ApiDemoTriggerSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/process-enrichment-jobs': {
      id: '/api/public/process-enrichment-jobs'
      path: '/api/public/process-enrichment-jobs'
      fullPath: '/api/public/process-enrichment-jobs'
      preLoaderRoute: typeof ApiPublicProcessEnrichmentJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/ai-phone-lead': {
      id: '/api/webhooks/ai-phone-lead'
      path: '/api/webhooks/ai-phone-lead'
      fullPath: '/api/webhooks/ai-phone-lead'
      preLoaderRoute: typeof ApiWebhooksAiPhoneLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug/': {
      id: '/b/$slug/'
      path: '/'
      fullPath: '/b/$slug/'
      preLoaderRoute: typeof BSlugIndexRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/b/$slug/chat': {
      id: '/b/$slug/chat'
      path: '/chat'
      fullPath: '/b/$slug/chat'
      preLoaderRoute: typeof BSlugChatRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/b/$slug/confirmation': {
      id: '/b/$slug/confirmation'
      path: '/confirmation'
      fullPath: '/b/$slug/confirmation'
      preLoaderRoute: typeof BSlugConfirmationRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/b/$slug/missed-call': {
      id: '/b/$slug/missed-call'
      path: '/missed-call'
      fullPath: '/b/$slug/missed-call'
      preLoaderRoute: typeof BSlugMissedCallRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/b/$slug/request': {
      id: '/b/$slug/request'
      path: '/request'
      fullPath: '/b/$slug/request'
      preLoaderRoute: typeof BSlugRequestRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/api/public/billing/checkout': {
      id: '/api/public/billing/checkout'
      path: '/api/public/billing/checkout'
      fullPath: '/api/public/billing/checkout'
      preLoaderRoute: typeof ApiPublicBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/portal': {
      id: '/api/public/billing/portal'
      path: '/api/public/billing/portal'
      fullPath: '/api/public/billing/portal'
      preLoaderRoute: typeof ApiPublicBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/summary': {
      id: '/api/public/billing/summary'
      path: '/api/public/billing/summary'
      fullPath: '/api/public/billing/summary'
      preLoaderRoute: typeof ApiPublicBillingSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe-inbound': {
      id: '/api/public/webhooks/stripe-inbound'
      path: '/api/public/webhooks/stripe-inbound'
      fullPath: '/api/public/webhooks/stripe-inbound'
      preLoaderRoute: typeof ApiPublicWebhooksStripeInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/vapi-inbound': {
      id: '/api/public/webhooks/vapi-inbound'
      path: '/api/public/webhooks/vapi-inbound'
      fullPath: '/api/public/webhooks/vapi-inbound'
      preLoaderRoute: typeof ApiPublicWebhooksVapiInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/twilio-missed-call/$slug': {
      id: '/api/public/webhooks/twilio-missed-call/$slug'
      path: '/api/public/webhooks/twilio-missed-call/$slug'
      fullPath: '/api/public/webhooks/twilio-missed-call/$slug'
      preLoaderRoute: typeof ApiPublicWebhooksTwilioMissedCallSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiReceptionistRoute: typeof AuthenticatedAiReceptionistRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMissedCallSettingsRoute: typeof AuthenticatedMissedCallSettingsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiReceptionistRoute: AuthenticatedAiReceptionistRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMissedCallSettingsRoute: AuthenticatedMissedCallSettingsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BSlugRouteChildren {
  BSlugChatRoute: typeof BSlugChatRoute
  BSlugConfirmationRoute: typeof BSlugConfirmationRoute
  BSlugMissedCallRoute: typeof BSlugMissedCallRoute
  BSlugRequestRoute: typeof BSlugRequestRoute
  BSlugIndexRoute: typeof BSlugIndexRoute
}

const BSlugRouteChildren: BSlugRouteChildren = {
  BSlugChatRoute: BSlugChatRoute,
  BSlugConfirmationRoute: BSlugConfirmationRoute,
  BSlugMissedCallRoute: BSlugMissedCallRoute,
  BSlugRequestRoute: BSlugRequestRoute,
  BSlugIndexRoute: BSlugIndexRoute,
}

const BSlugRouteWithChildren = BSlugRoute._addFileChildren(BSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AreasRoute: AreasRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  ConfirmationRoute: ConfirmationRoute,
  McpRoute: McpRoute,
  MissedCallRoute: MissedCallRoute,
  RequestRoute: RequestRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BSlugRoute: BSlugRouteWithChildren,
  ServicesBlockedDrainsRoute: ServicesBlockedDrainsRoute,
  ServicesEmergencyRoute: ServicesEmergencyRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiDashboardVerifyPinRoute: ApiDashboardVerifyPinRoute,
  ApiDemoTriggerSmsRoute: ApiDemoTriggerSmsRoute,
  ApiPublicProcessEnrichmentJobsRoute: ApiPublicProcessEnrichmentJobsRoute,
  ApiWebhooksAiPhoneLeadRoute: ApiWebhooksAiPhoneLeadRoute,
  ApiPublicBillingCheckoutRoute: ApiPublicBillingCheckoutRoute,
  ApiPublicBillingPortalRoute: ApiPublicBillingPortalRoute,
  ApiPublicBillingSummaryRoute: ApiPublicBillingSummaryRoute,
  ApiPublicWebhooksStripeInboundRoute: ApiPublicWebhooksStripeInboundRoute,
  ApiPublicWebhooksVapiInboundRoute: ApiPublicWebhooksVapiInboundRoute,
  ApiPublicWebhooksTwilioMissedCallSlugRoute:
    ApiPublicWebhooksTwilioMissedCallSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
